package ar.edu.unlar.paradigmas3.sistemagal.ui;

/**
 * @author Mateo.Bazan
 */
public class SgalGUI extends javax.swing.JFrame {

    /**
     * Creates new form SgalGUI
     */
    public SgalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkgSistGAL = new javax.swing.JPanel();
        dPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barMenu = new javax.swing.JMenuBar();
        menuAccidentes = new javax.swing.JMenu();
        abmAccidentes = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        abmEmpleados = new javax.swing.JMenuItem();
        menuTipoAccidente = new javax.swing.JMenu();
        abmTipoAccidente = new javax.swing.JMenuItem();
        menuMotivos = new javax.swing.JMenu();
        abmMotivo = new javax.swing.JMenuItem();
        menuZonaCuerpo = new javax.swing.JMenu();
        abmZonaCuerpo = new javax.swing.JMenuItem();
        menuParteCuerpo = new javax.swing.JMenu();
        abmPartesCuerpo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestión Accidentes Laborales");
        setLocationByPlatform(true);
        setResizable(false);

        bkgSistGAL.setBackground(new java.awt.Color(0, 51, 102));
        bkgSistGAL.setForeground(new java.awt.Color(0, 51, 102));

        dPane.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE GESTIÓN DE ACCIDENTES LABORALES");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo.Bazan\\OneDrive\\OneDrive - TSOFT\\Escritorio\\SistemaGAL\\src\\main\\java\\ar\\edu\\unlar\\paradigmas3\\sistemagal\\ui\\img\\homeIcon.png")); // NOI18N

        dPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dPaneLayout = new javax.swing.GroupLayout(dPane);
        dPane.setLayout(dPaneLayout);
        dPaneLayout.setHorizontalGroup(
            dPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPaneLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(dPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dPaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(397, 397, 397))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dPaneLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72))))
        );
        dPaneLayout.setVerticalGroup(
            dPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPaneLayout.createSequentialGroup()
                .addGroup(dPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dPaneLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel1)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bkgSistGALLayout = new javax.swing.GroupLayout(bkgSistGAL);
        bkgSistGAL.setLayout(bkgSistGALLayout);
        bkgSistGALLayout.setHorizontalGroup(
            bkgSistGALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dPane)
        );
        bkgSistGALLayout.setVerticalGroup(
            bkgSistGALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgSistGALLayout.createSequentialGroup()
                .addComponent(dPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        menuAccidentes.setText("Accidentes");

        abmAccidentes.setText("ABM Accidentes");
        abmAccidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmAccidentesActionPerformed(evt);
            }
        });
        menuAccidentes.add(abmAccidentes);

        barMenu.add(menuAccidentes);

        menuEmpleados.setText("Empleados");

        abmEmpleados.setText("ABM Empleados");
        abmEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmEmpleadosActionPerformed(evt);
            }
        });
        menuEmpleados.add(abmEmpleados);

        barMenu.add(menuEmpleados);

        menuTipoAccidente.setText("Tipos Accidentes");

        abmTipoAccidente.setText("ABM Tipo accidentes");
        abmTipoAccidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmTipoAccidenteActionPerformed(evt);
            }
        });
        menuTipoAccidente.add(abmTipoAccidente);

        barMenu.add(menuTipoAccidente);

        menuMotivos.setText("Motivos");

        abmMotivo.setText("ABM Motivos");
        abmMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmMotivoActionPerformed(evt);
            }
        });
        menuMotivos.add(abmMotivo);

        barMenu.add(menuMotivos);

        menuZonaCuerpo.setText("Zonas Cuerpo");

        abmZonaCuerpo.setText("ABM Zonas Cuerpo");
        abmZonaCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmZonaCuerpoActionPerformed(evt);
            }
        });
        menuZonaCuerpo.add(abmZonaCuerpo);

        barMenu.add(menuZonaCuerpo);

        menuParteCuerpo.setText("Partes Cuerpo");

        abmPartesCuerpo.setText("ABM Partes Cuerpo");
        abmPartesCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmPartesCuerpoActionPerformed(evt);
            }
        });
        menuParteCuerpo.add(abmPartesCuerpo);

        barMenu.add(menuParteCuerpo);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgSistGAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgSistGAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abmEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmEmpleadosActionPerformed
        ABMEmpleado abmEmpleado = new ABMEmpleado();
        dPane.add(abmEmpleado);
        abmEmpleado.setVisible(true);
    }//GEN-LAST:event_abmEmpleadosActionPerformed

    private void abmTipoAccidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmTipoAccidenteActionPerformed
        ABMTipoAccidente aBMTipoAccidente = new ABMTipoAccidente();
        dPane.add(aBMTipoAccidente);
        aBMTipoAccidente.setVisible(true);
    }//GEN-LAST:event_abmTipoAccidenteActionPerformed

    private void abmPartesCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmPartesCuerpoActionPerformed
        ABMParteCuerpo aBMParteCuerpo = new ABMParteCuerpo();
        dPane.add(aBMParteCuerpo);
        aBMParteCuerpo.setVisible(true);
    }//GEN-LAST:event_abmPartesCuerpoActionPerformed

    private void abmAccidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmAccidentesActionPerformed
        ABMAccidente aBMAccidente = new ABMAccidente();
        dPane.add(aBMAccidente);
        aBMAccidente.setVisible(true);
    }//GEN-LAST:event_abmAccidentesActionPerformed

    private void abmMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmMotivoActionPerformed
        ABMMotivo abmMotivo = new ABMMotivo();
        dPane.add(abmMotivo);
        abmMotivo.setVisible(true);
    }//GEN-LAST:event_abmMotivoActionPerformed

    private void abmZonaCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmZonaCuerpoActionPerformed
        ABMZonaCuerpo aBMZonaCuerpo = new ABMZonaCuerpo();
        dPane.add(aBMZonaCuerpo);
        aBMZonaCuerpo.setVisible(true);
    }//GEN-LAST:event_abmZonaCuerpoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SgalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SgalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SgalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SgalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SgalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abmAccidentes;
    private javax.swing.JMenuItem abmEmpleados;
    private javax.swing.JMenuItem abmMotivo;
    private javax.swing.JMenuItem abmPartesCuerpo;
    private javax.swing.JMenuItem abmTipoAccidente;
    private javax.swing.JMenuItem abmZonaCuerpo;
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JPanel bkgSistGAL;
    private javax.swing.JDesktopPane dPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu menuAccidentes;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenu menuMotivos;
    private javax.swing.JMenu menuParteCuerpo;
    private javax.swing.JMenu menuTipoAccidente;
    private javax.swing.JMenu menuZonaCuerpo;
    // End of variables declaration//GEN-END:variables
}
