/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ar.edu.unlar.paradigmas3.sistemagal.ui.forms;

import ar.edu.unlar.paradigmas3.sistemagal.objetos.Accidente;
import ar.edu.unlar.paradigmas3.sistemagal.objetos.controladores.Accidente_Controller;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateo.Bazan
 */
public class AccidentesForm extends javax.swing.JFrame {

    /**
     * Creates new form AccidentesForm
     */
    public AccidentesForm() {
        initComponents();

        Accidente_Controller aController = new Accidente_Controller();
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Numero");
        model.addColumn("Fecha");
        model.addColumn("Ubicacion");
        model.addColumn("LegajoEmpleado");
        model.addColumn("CodigoMotivo");
        model.addColumn("CodigoTipoAccidente");

        ArrayList<Accidente> data = aController.getAccidentesPreZona();

        for (Accidente accidente : data) {

            Object[] rowData = {
                accidente.getNumero(), accidente.getFecha(), accidente.getUbicacion(), accidente.getLegajoEmpleado().getLegajo(), accidente.getCodigoMotivo().getCodigo(), accidente.getCodigoTipoAccidente().getCodigo(),};

            model.addRow(rowData);

        }

        tblAccidentes.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accidenteGrillaB1 = new ar.edu.unlar.paradigmas3.sistemagal.grillas.AccidenteGrillaB();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccidentes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accidentes");

        tblAccidentes.setModel(accidenteGrillaB1);
        jScrollPane1.setViewportView(tblAccidentes);
        if (tblAccidentes.getColumnModel().getColumnCount() > 0) {
            tblAccidentes.getColumnModel().getColumn(0).setHeaderValue("Numero");
            tblAccidentes.getColumnModel().getColumn(1).setHeaderValue("Fecha");
            tblAccidentes.getColumnModel().getColumn(2).setHeaderValue("Ubicacion");
            tblAccidentes.getColumnModel().getColumn(3).setHeaderValue("LegajoEmpleado");
            tblAccidentes.getColumnModel().getColumn(4).setHeaderValue("CodigoMotivo");
            tblAccidentes.getColumnModel().getColumn(5).setHeaderValue("CodigoTipoAccidente");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccidentesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccidentesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccidentesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccidentesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccidentesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ar.edu.unlar.paradigmas3.sistemagal.grillas.AccidenteGrillaB accidenteGrillaB1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAccidentes;
    // End of variables declaration//GEN-END:variables
}
